# Data Science Project - Group 3

## Introduction

## The Dataset

brief overview of our methods
we collected data using form
asked about blablah

## Overview of the Data Collected

Before we start cleaning the data, we first need to look into the data and see if there are blablah..

In [1]:
#Import Libraries

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import scipy as sc

In [2]:
#read the file
df = pd.read_csv("file.csv")

df.shape

(107, 32)

Lets first take a few snapshots of our data.

In [3]:
df.head(5)

,Timestamp,What is your age?,What is your gender?,Where do you live?,What is your monthly budget?,How much do you spend on food every month?,How do you primarily pay for your food?,Do you work on campus/outside?,Which specific diet plan do you follow?,Do you have any diet related allergies?,...,How often do you eat at Green Olive per week?,How often do you eat at Bunker per week?,How often do you eat at Baithak per week?,How often do you eat from outside of Lums per week?,On a scale 1 to 5 rate how satisfied you are with eating options at campus,Do you prefer takeaways or deliveries?,What time do you usually get Takeaways?,What time do you usually get Deliveries?,How would you describe your eating habits on a scale of 1 to 5,How would you describe how healthy you are on a scale of 1 to 5
0,17/10/2024 19:46:41,23,Male,Day scholar,"10,000 - 15,000","5,000 - 10,000",Parental/Family support,TAs,High Protein,No,...,Never,Never,Never,1-2 times per week,1,Takeaways,Dinner,"Dinner, Late night",3,3
1,17/10/2024 19:46:50,22,Female,Day scholar,"25,000 - 30,000","10,000 - 15,000",Parental/Family support,TAs,I eat everything,No,...,sometimes,Never,3-4 times per week,5-6 times per week,4,Deliveries,Early Dinner,"Early Dinner, Dinner",1,3
2,17/10/2024 19:49:03,22,Female,Day scholar,"15,000 - 20,000","10,000 - 15,000",Parental/Family support,TAs,I eat everything,No,...,Never,Never,1-2 times per week,1-2 times per week,4,Deliveries,"Lunch,",Late night,3,2
3,17/10/2024 19:49:17,22,Female,Hostelite but living in Lahore,"20,000 - 25,000","15,000 - 20,000",Earning from a job,Job/Freelance,I eat everything,No,...,1-2 times per week,Never,1-2 times per week,1-2 times per week,3,Deliveries,"Breakfast, Brunch, Lunch, Early Dinner, Dinner...","Breakfast, Brunch, Lunch, Early Dinner, Dinner...",2,2
4,17/10/2024 19:53:22,25,Female,Day scholar,"15,000 - 20,000","5,000 - 10,000",Parental/Family support,I don’t work,I eat everything,No,...,Never,Never,Never,Never,3,Deliveries,Lunch,Dinner,3,3

In [4]:
# Check for missing values in the entire DataFrame
missing_values = df.isnull().sum()

# Filter and display columns with missing values
missing_report = missing_values[missing_values > 0]

if not missing_report.empty:
    print("Columns with missing values:")
    print(missing_report)
else:
    print("No missing values in the DataFrame.")

Columns with missing values:
If you said Yes to above question, please specify which allergy.    101
dtype: int64

In [5]:
# Data types of each col
print("Data types of each column:")
print(df.dtypes)

Data types of each column:
Timestamp                                                                     object
What is your age?                                                              int64
What is your gender?                                                          object
Where do you live?                                                            object
What is your monthly budget?                                                  object
How much do you spend on food every month?                                    object
How do you primarily pay for your food?                                       object
Do you work on campus/outside?                                                object
Which specific diet plan do you follow?                                       object
Do you have any diet related allergies?                                       object
If you said Yes to above question, please specify which allergy.              object
How often you cook your own meals in a week?                                  object
How often do you eat at PDC per week?                                         object
How often do you eat at Baradari  per week?                                   object
How often do you eat at Khokha  per week?                                     object
How often do you eat at Superstore  per week?                                 object
How often do you eat at Zakir Tikka  per week?                                object
How often do you eat at Juice Zone per week?                                  object
How often do you eat at Subway per week?                                      object
How often do you eat at Chop Chop per week?                                   object
How often do you eat at Delish per week?                                      object
How often do you eat at Jammin per week?                                      object
How often do you eat at Green Olive per week?                                 object
How often do you eat at Bunker per week?                                      object
How often do you eat at Baithak per week?                                     object
How often do you eat from outside of Lums per week?                           object
On a scale 1 to 5 rate how satisfied you are with eating options at campus     int64
Do you prefer takeaways or deliveries?                                        object
What time do you usually get Takeaways?                                       object
What time do you usually get Deliveries?                                      object
How would you describe your eating habits on a scale of 1 to 5                 int64
How would you describe how healthy you are on a scale of 1 to 5                int64
dtype: object

In [6]:
# Get all categorical columns (object type or explicitly set as categorical)
categorical_cols = df.select_dtypes(include=['object', 'category']).columns[1:] #remove timestamp col from here


# Display unique values for each categorical column
for col in categorical_cols:
    unique_values = df[col].unique()
    print(f"Unique values in '{col}': {unique_values}")

Unique values in 'What is your gender?': ['Male' 'Female' 'Prefer not to say']
Unique values in 'Where do you live?': ['Day scholar' 'Hostelite but living in Lahore' 'Hostelite']
Unique values in 'What is your monthly budget?': ['10,000 - 15,000' '25,000 - 30,000' '15,000 - 20,000' '20,000 - 25,000'
 '45,000 - 50,000' '5,000 - 10,000' '60000' '30,000 - 35,000'
 'less than 5000' '35,000 - 40, 000' '40,000 - 45,000' '60k']
Unique values in 'How much do you spend on food every month?': ['5,000 - 10,000' '10,000 - 15,000' '15,000 - 20,000' '2,000 - 5,000'
 'Almost all of it' '28000' '25000' '30000' '35000' '1000-2000' '25000+'
 '50000' '50k' '40k+' '32,000-35,000' '30-35k' '25-30k']
Unique values in 'How do you primarily pay for your food?': ['Parental/Family support' 'Earning from a job'
 'Parental/Family support, Financial Aid'
 'Parental/Family support, Earning from a job'
 'Personal Savings, Parental/Family support, Earning from a job'
 'Personal Savings' 'Personal Savings, Earning from a job'
 'Personal Savings, Parental/Family support' 'My own business'
 'Personal Savings, Parental/Family support, Financial Aid, Earning from a job']
Unique values in 'Do you work on campus/outside?': ['TAs' 'Job/Freelance' 'I don’t work' 'Other jobs on campus' 'RAs']
Unique values in 'Which specific diet plan do you follow?': ['High Protein' 'I eat everything' 'I eat everything except chicken'
 'Low carb' 'Not any specific plan' 'Gluten free']
Unique values in 'Do you have any diet related allergies?': ['No' 'Yes']
Unique values in 'If you said Yes to above question, please specify which allergy.': [nan 'Peanuts, eggs, banana' '_' 'Probably Lactose Intolerant ' 'Gluten'
 'I have celiac disease ' 'peanuts']
Unique values in 'How often you cook your own meals in a week?': ['Never' '1-2 times per week' 'once or twice a month' '7-8 times per week'
 '3-4 times per week' '5-6 times per week' 'sometimes (2-3 times a month)'
 'I only make instant oats and toast']
Unique values in 'How often do you eat at PDC per week?': ['1-2 times per week' 'Never' '5-6 times per week' '3-4 times per week'
 '7-8 times per week' 'Easy 12+ times in a week' '10-12 times per week'
 'rarely']
Unique values in 'How often do you eat at Baradari  per week?': ['Never' '1-2 times per week' '1 or 2 times every 2 weeks'
 '5-6 times per week' '3-4 times per week' 'once a month']
Unique values in 'How often do you eat at Khokha  per week?': ['1-2 times per week' 'Never' '3-4 times per week'
 'Ate 1 time and got sick so never now'
 'rarely but I get snacks sometimes' '7-8 times per week']
Unique values in 'How often do you eat at Superstore  per week?': ['3-4 times per week' '7-8 times per week' 'Never' '1-2 times per week'
 '5-6 times per week' 'rarely but I have coffee from there']
Unique values in 'How often do you eat at Zakir Tikka  per week?': ['Never' '1-2 times per week' '5-6 times per week' '3-4 times per week'
 'rarely']
Unique values in 'How often do you eat at Juice Zone per week?': ['Never' '1-2 times per week' '3-4 times per week' 'only chai']
Unique values in 'How often do you eat at Subway per week?': ['Never' '1-2 times per week' '3-4 times per week' '5-6 times per week'
 'Twice a month' '3-4 times a semester']
Unique values in 'How often do you eat at Chop Chop per week?': ['Never' '1-2 times per week' 'once in a month or two months'
 'Once a month']
Unique values in 'How often do you eat at Delish per week?': ['Never' '1-2 times per week' '3-4 times per week'
 'once or twice a semester' '5-6 times per week'
 'Very rarely. Their quality has gone down'
 'Sometimes. Not on weekly basis' 'Once a month' '4-5 times per semester']
Unique values in 'How often do you eat at Jammin per week?': ['Never' '3-4 times per week' '1-2 times per week' 'Rarely' 'Once a month'
 'Twice or thrice a month' '7-8 times per week']
Unique values in 'How often do you eat at Green Olive per week?': ['Never' 'sometimes' '1-2 times per week' 'once twicw semester'
 '3-4 times per week' 'Sometimes ']
Unique values in 'How often do you eat at Bunker per week?': ['Never' '3-4 times per week' 'once or twice semester'
 '1-2 times per week' '7-8 times per week']
Unique values in 'How often do you eat at Baithak per week?': ['Never' '3-4 times per week' '1-2 times per week' '5-6 times per week'
 '7-8 times per week' 'Chai only']
Unique values in 'How often do you eat from outside of Lums per week?': ['1-2 times per week' '5-6 times per week' 'Never' '3-4 times per week'
 '7-8 times per week' '1 or 2 times a month' 'Only colour days'
 'I eat at home bruh' 'rarely']
Unique values in 'Do you prefer takeaways or deliveries?': ['Takeaways' 'Deliveries']
Unique values in 'What time do you usually get Takeaways?  ': ['Dinner' 'Early Dinner' 'Lunch, '
 'Breakfast, Brunch, Lunch, Early Dinner, Dinner, Late night' 'Lunch'
 'Lunch, Dinner' 'Lunch, Early Dinner' 'Late night' 'Don’t '
 'Lunch, Early Dinner, Dinner' 'I dont get takeaways'
 'I don’t get takeaways' 'Brunch, Lunch, Early Dinner'
 "I don't do takeaways" 'Breakfast, Lunch' 'Early Dinner, Dinner'
 'Early Dinner, I don’t get takeaways' 'Early Dinner, Late night'
 'Lunch, Early Dinner, I don’t get takeaways' 'Lunch, Dinner, Late night'
 'Dinner, Late night' 'Breakfast' 'Early Dinner, Dinner, Late night'
 'Breakfast, Brunch, Lunch, Early Dinner, Dinner, Late night, I don’t get takeaways'
 'Brunch, Lunch' 'I dont' 'Breakfast, Early Dinner, Late night'
 'Breakfast, Dinner' 'Brunch, Dinner' 'Lunch, I don’t get takeaways']
Unique values in 'What time do you usually get Deliveries?  ': ['Dinner, Late night' 'Early Dinner, Dinner' 'Late night'
 'Breakfast, Brunch, Lunch, Early Dinner, Dinner, Late night' 'Dinner'
 'Lunch, Dinner' 'Lunch, Early Dinner, Dinner'
 'Breakfast, Dinner, Late night' 'Early Dinner' 'Lunch'
 'Lunch, Late night' 'Early Dinner, Dinner, Late night' "Usually don't "
 'Lunch, Early Dinner, Dinner, Late night' 'Nothing '
 'Lunch, Early Dinner' 'Brunch, Lunch, Early Dinner, Dinner, Late night'
 'Not really' "I don't bruh" 'Breakfast, Early Dinner, Late night'
 'Lunch, Dinner, Late night'
 'Late night, tbh 5am is closer to early morning so yeah' 'Nahi kartay'
 'Breakfast' 'Breakfast, Lunch, Early Dinner, Dinner, Late night']

### Some Observations

- Categorical Values in different col such as Male/Female etc -- these need to be cleaned
- Missing Values in type of allergy col -- these need to be cleaned
- Very long col names - need to be changed for consistency
- Range values in col such as monthly budget, spent money etc -- need to be cleaned

## DATA CLEANING

1. Let's first rename all columns and make them shoster for consistency and clarity.

| Original Column Name                                                                 | New Column Name          |
|---------------------------------------------------------------------------------------|--------------------------|
| what_is_your_age?                                                                     | age                      |
| what_is_your_gender?                                                                  | gender                   |
| where_do_you_live?                                                                    | location                 |
| what_is_your_monthly_budget?                                                           | monthly_budget           |
| how_much_do_you_spend_on_food_every_month?                                             | food_spending            |
| how_do_you_primarily_pay_for_your_food?                                                | payment_method           |
| do_you_work_on_campus/outside?                                                        | work_location            |
| which_specific_diet_plan_do_you_follow?                                                | diet_plan                |
| do_you_have_any_diet_related_allergies?                                                | allergies                |
| if_you_said_yes_to_above_question,_please_specify_which_allergy.                      | allergy_details          |
| how_often_you_cook_your_own_meals_in_a_week?                                           | cook_frequency           |
| how_often_do_you_eat_at_pdc_per_week?                                                  | eat_at_pdc               |
| how_often_do_you_eat_at_baradari__per_week?                                            | eat_at_baradari          |
| how_often_do_you_eat_at_khokha__per_week?                                              | eat_at_khokha            |
| how_often_do_you_eat_at_superstore__per_week?                                          | eat_at_superstore        |
| how_often_do_you_eat_at_zakir_tikka__per_week?                                         | eat_at_zakir_tikka       |
| how_often_do_you_eat_at_juice_zone_per_week?                                           | eat_at_juice_zone        |
| how_often_do_you_eat_at_subway_per_week?                                               | eat_at_subway            |
| how_often_do_you_eat_at_chop_chop_per_week?                                            | eat_at_chop_chop         |
| how_often_do_you_eat_at_delish_per_week?                                               | eat_at_delish            |
| how_often_do_you_eat_at_jammin_per_week?                                               | eat_at_jammin            |
| how_often_do_you_eat_at_green_olive_per_week?                                          | eat_at_green_olive       |
| how_often_do_you_eat_at_bunker_per_week?                                               | eat_at_bunker            |
| how_often_do_you_eat_at_baithak_per_week?                                              | eat_at_baithak           |
| how_often_do_you_eat_from_outside_of_lums_per_week?                                    | eat_outside_lums         |
| on_a_scale_1_to_5_rate_how_satisfied_you_are_with_eating_options_at_campus            | campus_food_satisfaction |
| do_you_prefer_takeaways_or_deliveries?                                                 | takeaway_or_delivery     |
| what_time_do_you_usually_get_takeaways?                                                | takeaway_time            |
| what_time_do_you_usually_get_deliveries?                                               | delivery_time            |
| how_would_you_describe_your_eating_habits_on_a_scale_of_1_to_5                         |  health_rating|

In [7]:
print(df.columns)

Index(['Timestamp', 'What is your age?', 'What is your gender?',
       'Where do you live?', 'What is your monthly budget?',
       'How much do you spend on food every month?',
       'How do you primarily pay for your food?',
       'Do you work on campus/outside?',
       'Which specific diet plan do you follow?',
       'Do you have any diet related allergies?',
       'If you said Yes to above question, please specify which allergy.',
       'How often you cook your own meals in a week?',
       'How often do you eat at PDC per week?',
       'How often do you eat at Baradari  per week?',
       'How often do you eat at Khokha  per week?',
       'How often do you eat at Superstore  per week?',
       'How often do you eat at Zakir Tikka  per week?',
       'How often do you eat at Juice Zone per week?',
       'How often do you eat at Subway per week?',
       'How often do you eat at Chop Chop per week?',
       'How often do you eat at Delish per week?',
       'How often do you eat at Jammin per week?',
       'How often do you eat at Green Olive per week?',
       'How often do you eat at Bunker per week?',
       'How often do you eat at Baithak per week?',
       'How often do you eat from outside of Lums per week?',
       'On a scale 1 to 5 rate how satisfied you are with eating options at campus',
       'Do you prefer takeaways or deliveries?',
       'What time do you usually get Takeaways?  ',
       'What time do you usually get Deliveries?  ',
       'How would you describe your eating habits on a scale of 1 to 5',
       'How would you describe how healthy you are on a scale of 1 to 5'],
      dtype='object')

In [8]:
# Renaming columns using a dictionary for clarity
column_renaming = {
    'Timestamp' : 'timestamp',
    'What is your age?': 'age',
    'What is your gender?': 'gender',
    'Where do you live?': 'location',
    'What is your monthly budget?': 'monthly_budget',
    'How much do you spend on food every month?': 'food_spending',
    'How do you primarily pay for your food?': 'payment_method',
    'Do you work on campus/outside?': 'work_location',
    'Which specific diet plan do you follow?': 'diet_plan',
    'Do you have any diet related allergies?': 'allergies',
    'If you said Yes to above question, please specify which allergy.': 'allergy_details',
    'How often you cook your own meals in a week?': 'cook_frequency',
    'How often do you eat at PDC per week?': 'eat_at_pdc',
    'How often do you eat at Baradari  per week?': 'eat_at_baradari',
    'How often do you eat at Khokha  per week?': 'eat_at_khokha',
    'How often do you eat at Superstore  per week?': 'eat_at_superstore',
    'How often do you eat at Zakir Tikka  per week?': 'eat_at_zakir_tikka',
    'How often do you eat at Juice Zone per week?': 'eat_at_juice_zone',
    'How often do you eat at Subway per week?': 'eat_at_subway',
    'How often do you eat at Chop Chop per week?': 'eat_at_chop_chop',
    'How often do you eat at Delish per week?': 'eat_at_delish',
    'How often do you eat at Jammin per week?': 'eat_at_jammin',
    'How often do you eat at Green Olive per week?': 'eat_at_green_olive',
    'How often do you eat at Bunker per week?': 'eat_at_bunker',
    'How often do you eat at Baithak per week?': 'eat_at_baithak',
    'How often do you eat from outside of Lums per week?': 'eat_outside_lums',
    'On a scale 1 to 5 rate how satisfied you are with eating options at campus': 'campus_food_satisfaction',
    'Do you prefer takeaways or deliveries?': 'takeaway_or_delivery',
    'What time do you usually get Takeaways?  ': 'takeaway_time',
    'What time do you usually get Deliveries?  ': 'delivery_time',
    'How would you describe your eating habits on a scale of 1 to 5': 'eating_habit_rating',
    'How would you describe how healthy you are on a scale of 1 to 5': 'health_rating'
}

In [9]:
df.columns = df.columns.map(column_renaming)

In [10]:
df.head(2)

,timestamp,age,gender,location,monthly_budget,food_spending,payment_method,work_location,diet_plan,allergies,...,eat_at_green_olive,eat_at_bunker,eat_at_baithak,eat_outside_lums,campus_food_satisfaction,takeaway_or_delivery,takeaway_time,delivery_time,eating_habit_rating,health_rating
0,17/10/2024 19:46:41,23,Male,Day scholar,"10,000 - 15,000","5,000 - 10,000",Parental/Family support,TAs,High Protein,No,...,Never,Never,Never,1-2 times per week,1,Takeaways,Dinner,"Dinner, Late night",3,3
1,17/10/2024 19:46:50,22,Female,Day scholar,"25,000 - 30,000","10,000 - 15,000",Parental/Family support,TAs,I eat everything,No,...,sometimes,Never,3-4 times per week,5-6 times per week,4,Deliveries,Early Dinner,"Early Dinner, Dinner",1,3

In [11]:
df.columns

Index(['timestamp', 'age', 'gender', 'location', 'monthly_budget',
       'food_spending', 'payment_method', 'work_location', 'diet_plan',
       'allergies', 'allergy_details', 'cook_frequency', 'eat_at_pdc',
       'eat_at_baradari', 'eat_at_khokha', 'eat_at_superstore',
       'eat_at_zakir_tikka', 'eat_at_juice_zone', 'eat_at_subway',
       'eat_at_chop_chop', 'eat_at_delish', 'eat_at_jammin',
       'eat_at_green_olive', 'eat_at_bunker', 'eat_at_baithak',
       'eat_outside_lums', 'campus_food_satisfaction', 'takeaway_or_delivery',
       'takeaway_time', 'delivery_time', 'eating_habit_rating',
       'health_rating'],
      dtype='object')

#### 2. Let's remove the 'timestamp' column, as it is not relevant to the data we collected (it only indicates when participants completed the survey).

In [12]:
df = df.drop(columns=['timestamp'])

#### 3. Now let's deal with the first half of categorical value

We'll deal with the following col (gender,location,work_location , allergies). The following table describes mappings we have done

##### Categorical Columns and Their Mappings

| Column Name           | Description                                         | Mapped Values (Numeric)                                |
|-----------------------|-----------------------------------------------------|--------------------------------------------------------|
| **Gender**            | Gender of the respondent                           | 'Male' (1), 'Female' (2), 'Prefer not to say' (3)     |
| **Location**          | Type of accommodation or living situation          | 'Day scholar' (1), 'Hostelite but living in Lahore' (2), 'Hostelite' (3) |
| **Work Location**     | Work or job-related status at campus               | 'TAs' (1), 'Job/Freelance' (2), 'I don’t work' (3), 'Other jobs on campus' (4), 'RAs' (5) |
| **Diet Plan**         | The respondent’s diet plan preference              | 'High Protein' (1), 'I eat everything' (2), 'I eat everything except chicken' (3), 'Low carb' (4), 'Not any specific plan' (5), 'Gluten free' (6) |
| **Allergies**         | Whether the respondent has any diet-related allergies | 'No' (0), 'Yes' (1)                                     |

In [13]:
# List of columns I want to get unique values for
columns_of_interest = ['gender', 'location', 'payment_method','work_location','diet_plan','allergies']

# Create a dictionary to store unique values for each column
unique_values = {col: df[col].unique() for col in columns_of_interest}

# Print the unique values for each column
for col, values in unique_values.items():
    print(f"Unique values in '{col}': {values}")

Unique values in 'gender': ['Male' 'Female' 'Prefer not to say']
Unique values in 'location': ['Day scholar' 'Hostelite but living in Lahore' 'Hostelite']
Unique values in 'payment_method': ['Parental/Family support' 'Earning from a job'
 'Parental/Family support, Financial Aid'
 'Parental/Family support, Earning from a job'
 'Personal Savings, Parental/Family support, Earning from a job'
 'Personal Savings' 'Personal Savings, Earning from a job'
 'Personal Savings, Parental/Family support' 'My own business'
 'Personal Savings, Parental/Family support, Financial Aid, Earning from a job']
Unique values in 'work_location': ['TAs' 'Job/Freelance' 'I don’t work' 'Other jobs on campus' 'RAs']
Unique values in 'diet_plan': ['High Protein' 'I eat everything' 'I eat everything except chicken'
 'Low carb' 'Not any specific plan' 'Gluten free']
Unique values in 'allergies': ['No' 'Yes']

In [14]:
# 1. Create mappings for each categorical column
gender_mapping = {
    'Male': 1,
    'Female': 2,
    'Prefer not to say': 3
}

location_mapping = {
    'Day scholar': 1,
    'Hostelite but living in Lahore': 2,
    'Hostelite': 3
}

work_location_mapping = {
    'TAs': 1,
    'Job/Freelance': 2,
    'I don’t work': 3,
    'Other jobs on campus': 4,
    'RAs': 5
}

diet_plan_mapping = {
    'High Protein': 1,
    'I eat everything': 2,
    'I eat everything except chicken': 3,
    'Low carb': 4,
    'Not any specific plan': 5,
    'Gluten free': 6
}

allergies_mapping = {
    'No' : 0,
    'Yes' : 1
}

# Applying the mappings to the relevant columns
df['gender'] = df['gender'].map(gender_mapping)
df['location'] = df['location'].map(location_mapping)
df['work_location'] = df['work_location'].map(work_location_mapping)
df['diet_plan'] = df['diet_plan'].map(diet_plan_mapping)
df['allergies'] = df['allergies'].map(allergies_mapping)

#### 4. One hot encodings

In this step, we applied **one-hot encoding** to the categorical columns `payment_methods`,  `takeaway_time` and `delivery_time`, which contained multiple comma-separated values. In these questions participants were allowed to choose multiple options. One-hot encoding is a method used to convert categorical data into a format where all information is preserved in numerical way.

##### `payment_methods` col

In [15]:


# The unique options that you want to one-hot encode
options = ['Personal Savings', 'Parental/Family support', 'Financial Aid', 'Earning from a job', 'My own business']

# Create a one-hot encoded DataFrame with a prefix for each column name
for option in options:
    # Create a new column with a prefix, making column names lowercase, removing spaces and shortening names
    optimized_option = option.replace(' ', '_').lower().replace(',', '').replace('/', '_')
    df[f'pay_{optimized_option}'] = df['payment_method'].apply(lambda x: 1 if option in x else 0)

# Drop the original 'payment_method' column as we no longer need it
df.drop('payment_method', axis=1, inplace=True)

##### `takeaway_time` and `delivery_time` columns

Lets first see the unique strings present in this column. Here participants were allowed to select multiple options.

In [16]:
# List of columns I want to get unique values for
columns_of_interest = ['takeaway_time', 'delivery_time']

# Create a dictionary to store unique values for each column
unique_values = {col: df[col].unique() for col in columns_of_interest}

# Print the unique values for each column
for col, values in unique_values.items():
    print(f"Unique values in '{col}': {values}")

Unique values in 'takeaway_time': ['Dinner' 'Early Dinner' 'Lunch, '
 'Breakfast, Brunch, Lunch, Early Dinner, Dinner, Late night' 'Lunch'
 'Lunch, Dinner' 'Lunch, Early Dinner' 'Late night' 'Don’t '
 'Lunch, Early Dinner, Dinner' 'I dont get takeaways'
 'I don’t get takeaways' 'Brunch, Lunch, Early Dinner'
 "I don't do takeaways" 'Breakfast, Lunch' 'Early Dinner, Dinner'
 'Early Dinner, I don’t get takeaways' 'Early Dinner, Late night'
 'Lunch, Early Dinner, I don’t get takeaways' 'Lunch, Dinner, Late night'
 'Dinner, Late night' 'Breakfast' 'Early Dinner, Dinner, Late night'
 'Breakfast, Brunch, Lunch, Early Dinner, Dinner, Late night, I don’t get takeaways'
 'Brunch, Lunch' 'I dont' 'Breakfast, Early Dinner, Late night'
 'Breakfast, Dinner' 'Brunch, Dinner' 'Lunch, I don’t get takeaways']
Unique values in 'delivery_time': ['Dinner, Late night' 'Early Dinner, Dinner' 'Late night'
 'Breakfast, Brunch, Lunch, Early Dinner, Dinner, Late night' 'Dinner'
 'Lunch, Dinner' 'Lunch, Early Dinner, Dinner'
 'Breakfast, Dinner, Late night' 'Early Dinner' 'Lunch'
 'Lunch, Late night' 'Early Dinner, Dinner, Late night' "Usually don't "
 'Lunch, Early Dinner, Dinner, Late night' 'Nothing '
 'Lunch, Early Dinner' 'Brunch, Lunch, Early Dinner, Dinner, Late night'
 'Not really' "I don't bruh" 'Breakfast, Early Dinner, Late night'
 'Lunch, Dinner, Late night'
 'Late night, tbh 5am is closer to early morning so yeah' 'Nahi kartay'
 'Breakfast' 'Breakfast, Lunch, Early Dinner, Dinner, Late night']

In [17]:
def get_unique_strings_from_list(value_list):
    unique_strings = set()  # To store unique strings
    for value in value_list:
        # Split each string by commas, strip spaces, and update the set
        unique_strings.update([val.strip() for val in value.split(',') if val.strip()])
    return unique_strings

# Get unique strings for each column
for col, values in unique_values.items():
    unique_strings = get_unique_strings_from_list(values)
    print(f"Unique values in '{col}': {unique_strings}")

Unique values in 'takeaway_time': {'Early Dinner', 'I dont get takeaways', 'Breakfast', 'Dinner', 'Late night', 'Lunch', 'Don’t', 'I dont', 'I don’t get takeaways', 'Brunch', "I don't do takeaways"}
Unique values in 'delivery_time': {'Early Dinner', 'Not really', 'tbh 5am is closer to early morning so yeah', 'Nothing', 'Breakfast', 'Dinner', 'Late night', 'Lunch', "I don't bruh", "Usually don't", 'Nahi kartay', 'Brunch'}

##### Standardization Map Description
The standardization_map is used to standardize variations of responses related to "takeaway preferences" in the dataset. Several responses indicate that participants do not use takeaways, often due to confusion with delivery options. Based on this assumption, the following mappings were applied to group similar responses under a common category:

- Variations such as "Don’t", "I dont get takeaways", "I don't do takeaways", "nahi", and others have been standardized to "No", indicating that the participant does not use takeaways.
- A few other responses, such as "Late night, tbh 5am is closer to early morning so yeah", were mapped to "Late night" based on the assumption that participants intended to indicate a time preference, not a takeaway preference.
- Some variations, like "Early Dinner, I don’t get takeaways", were mapped to "No" under the assumption that participants were confused between "takeaway" and "delivery" options, and intended to indicate no takeaway preference.

The goal of this standardization is to address the confusion where participants accidentally selected "takeaway" options, but correctly indicated their actual preferences (e.g., delivery) in subsequent column. By grouping these variations under consistent labels, we can ensure cleaner and more meaningful data analysis.

In [18]:
standardization_map = {
    # Variations of "don't get takeaways"
    "Don’t": "No",
    "Don’t ": "No",
    "I dont get takeaways": "No",
    "I don’t get takeaways": "No",
    "I dont": "No",
    "I don't do takeaways": "No",
    "Usually don't ": "No",
    "Not really": "No",
    "Nothing ": "No",
    'Nothing': "No",
    "I don't bruh": "No",
    "Nahi kartay": "No",
    "Late night, tbh 5am is closer to early morning so yeah" : "Late night",
    "Early Dinner, I don’t get takeaways" : "No",
    "Lunch, Early Dinner, I don’t get takeaways" : "No",
    "Breakfast, Brunch, Lunch, Early Dinner, Dinner, Late night, I don’t get takeaways" : "No",
    "Lunch, I don’t get takeaways": "No"
}
# Step 3: Function to standardize column values using the mapping
def standardize_column(df, column, mapping):
    df[column] = df[column].fillna('').replace(mapping)
    return df

# Apply the standardization to both columns
df = standardize_column(df, columns_of_interest[0], standardization_map)
df = standardize_column(df, columns_of_interest[1], standardization_map)

Now lets make one hot encodings

In [19]:
# List of columns I want to get unique values for
columns_of_interest = ['takeaway_time', 'delivery_time']

# Create a dictionary to store unique values for each column
unique_values = {col: df[col].unique() for col in columns_of_interest}

# # Print the unique values for each column
# for col, values in unique_values.items():
#     print(f"Unique values in '{col}': {values}")
    
def get_unique_strings_from_list(value_list):
    unique_strings = set()  # To store unique strings
    for value in value_list:
        # Split each string by commas, strip spaces, and update the set
        unique_strings.update([val.strip() for val in value.split(',') if val.strip()])
    return unique_strings

# # Get unique strings for each column
# for col, values in unique_values.items():
#     unique_strings = get_unique_strings_from_list(values)
#     print(f"Unique values in '{col}': {unique_strings}")

all_unique_times = set()

for col in columns_of_interest:
    unique_strings = get_unique_strings_from_list(df[col].dropna())  # Drop NaN values
    all_unique_times.update(unique_strings)

# convert col names to lowercase with '_'
def clean_column_name(name):
    return name.lower().replace(" ", "_")

# Step 2: Apply one-hot encoding based on the unique time slots
def one_hot_encode(df, column, unique_times):
    for time in unique_times:
        # Create a new binary column for each unique time slot
        df[f"{column}_{time}"] = df[column].fillna('').apply(lambda x: int(time in x))
    return df

# Step 3: Apply one-hot encoding to both 'takeaway_time' and 'delivery_time' columns
for col in columns_of_interest:
    df = one_hot_encode(df, col, all_unique_times)

# Show the updated DataFrame with one-hot encoded columns
df.head()

,age,gender,location,monthly_budget,food_spending,work_location,diet_plan,allergies,allergy_details,cook_frequency,...,takeaway_time_Late night,takeaway_time_Lunch,takeaway_time_Brunch,delivery_time_No,delivery_time_Early Dinner,delivery_time_Breakfast,delivery_time_Dinner,delivery_time_Late night,delivery_time_Lunch,delivery_time_Brunch
0,23,1,1,"10,000 - 15,000","5,000 - 10,000",1,1,0,NaN,Never,...,0,0,0,0,0,0,1,1,0,0
1,22,2,1,"25,000 - 30,000","10,000 - 15,000",1,2,0,NaN,Never,...,0,0,0,0,1,0,1,0,0,0
2,22,2,1,"15,000 - 20,000","10,000 - 15,000",1,2,0,NaN,1-2 times per week,...,0,1,0,0,0,0,0,1,0,0
3,22,2,2,"20,000 - 25,000","15,000 - 20,000",2,2,0,NaN,once or twice a month,...,1,1,1,0,1,1,1,1,1,1
4,25,2,1,"15,000 - 20,000","5,000 - 10,000",3,2,0,NaN,Never,...,0,1,0,0,0,0,1,0,0,0

In [20]:
# Clean column names after one-hot encoding
def clean_column_names(df):
    df.columns = [col.lower().replace(" ", "_") for col in df.columns]  # Apply lower and replace spaces
    return df


df = clean_column_names(df)

In [21]:
df.columns

Index(['age', 'gender', 'location', 'monthly_budget', 'food_spending',
       'work_location', 'diet_plan', 'allergies', 'allergy_details',
       'cook_frequency', 'eat_at_pdc', 'eat_at_baradari', 'eat_at_khokha',
       'eat_at_superstore', 'eat_at_zakir_tikka', 'eat_at_juice_zone',
       'eat_at_subway', 'eat_at_chop_chop', 'eat_at_delish', 'eat_at_jammin',
       'eat_at_green_olive', 'eat_at_bunker', 'eat_at_baithak',
       'eat_outside_lums', 'campus_food_satisfaction', 'takeaway_or_delivery',
       'takeaway_time', 'delivery_time', 'eating_habit_rating',
       'health_rating', 'pay_personal_savings', 'pay_parental_family_support',
       'pay_financial_aid', 'pay_earning_from_a_job', 'pay_my_own_business',
       'takeaway_time_no', 'takeaway_time_early_dinner',
       'takeaway_time_breakfast', 'takeaway_time_dinner',
       'takeaway_time_late_night', 'takeaway_time_lunch',
       'takeaway_time_brunch', 'delivery_time_no',
       'delivery_time_early_dinner', 'delivery_time_breakfast',
       'delivery_time_dinner', 'delivery_time_late_night',
       'delivery_time_lunch', 'delivery_time_brunch'],
      dtype='object')

In [22]:
df.head(3)

,age,gender,location,monthly_budget,food_spending,work_location,diet_plan,allergies,allergy_details,cook_frequency,...,takeaway_time_late_night,takeaway_time_lunch,takeaway_time_brunch,delivery_time_no,delivery_time_early_dinner,delivery_time_breakfast,delivery_time_dinner,delivery_time_late_night,delivery_time_lunch,delivery_time_brunch
0,23,1,1,"10,000 - 15,000","5,000 - 10,000",1,1,0,NaN,Never,...,0,0,0,0,0,0,1,1,0,0
1,22,2,1,"25,000 - 30,000","10,000 - 15,000",1,2,0,NaN,Never,...,0,0,0,0,1,0,1,0,0,0
2,22,2,1,"15,000 - 20,000","10,000 - 15,000",1,2,0,NaN,1-2 times per week,...,0,1,0,0,0,0,0,1,0,0

In [23]:
df.columns

Index(['age', 'gender', 'location', 'monthly_budget', 'food_spending',
       'work_location', 'diet_plan', 'allergies', 'allergy_details',
       'cook_frequency', 'eat_at_pdc', 'eat_at_baradari', 'eat_at_khokha',
       'eat_at_superstore', 'eat_at_zakir_tikka', 'eat_at_juice_zone',
       'eat_at_subway', 'eat_at_chop_chop', 'eat_at_delish', 'eat_at_jammin',
       'eat_at_green_olive', 'eat_at_bunker', 'eat_at_baithak',
       'eat_outside_lums', 'campus_food_satisfaction', 'takeaway_or_delivery',
       'takeaway_time', 'delivery_time', 'eating_habit_rating',
       'health_rating', 'pay_personal_savings', 'pay_parental_family_support',
       'pay_financial_aid', 'pay_earning_from_a_job', 'pay_my_own_business',
       'takeaway_time_no', 'takeaway_time_early_dinner',
       'takeaway_time_breakfast', 'takeaway_time_dinner',
       'takeaway_time_late_night', 'takeaway_time_lunch',
       'takeaway_time_brunch', 'delivery_time_no',
       'delivery_time_early_dinner', 'delivery_time_breakfast',
       'delivery_time_dinner', 'delivery_time_late_night',
       'delivery_time_lunch', 'delivery_time_brunch'],
      dtype='object')

In [24]:
# Drop the original 'takeaway_time' column if you no longer need it
df.drop('takeaway_time', axis=1, inplace=True)
df.drop('delivery_time', axis=1, inplace=True)

In [25]:
df.columns

Index(['age', 'gender', 'location', 'monthly_budget', 'food_spending',
       'work_location', 'diet_plan', 'allergies', 'allergy_details',
       'cook_frequency', 'eat_at_pdc', 'eat_at_baradari', 'eat_at_khokha',
       'eat_at_superstore', 'eat_at_zakir_tikka', 'eat_at_juice_zone',
       'eat_at_subway', 'eat_at_chop_chop', 'eat_at_delish', 'eat_at_jammin',
       'eat_at_green_olive', 'eat_at_bunker', 'eat_at_baithak',
       'eat_outside_lums', 'campus_food_satisfaction', 'takeaway_or_delivery',
       'eating_habit_rating', 'health_rating', 'pay_personal_savings',
       'pay_parental_family_support', 'pay_financial_aid',
       'pay_earning_from_a_job', 'pay_my_own_business', 'takeaway_time_no',
       'takeaway_time_early_dinner', 'takeaway_time_breakfast',
       'takeaway_time_dinner', 'takeaway_time_late_night',
       'takeaway_time_lunch', 'takeaway_time_brunch', 'delivery_time_no',
       'delivery_time_early_dinner', 'delivery_time_breakfast',
       'delivery_time_dinner', 'delivery_time_late_night',
       'delivery_time_lunch', 'delivery_time_brunch'],
      dtype='object')

#### 5. Missing Values

We observed that the allergy_details column contains missing values, which is likely because most participants reported not having any allergies, as indicated in the allergies column. Since the allergy_details question was optional in the original survey, participants without allergies left this field blank.
to fill missing values we will replace missing values with 'no allergies'

In [26]:
df['allergy_details'] = df['allergy_details'].fillna('No allergies')